FROM rocker/rstudio:latest
RUN apt-get update
RUN apt-get install -y libpng-dev
RUN apt-get install wget -y
RUN wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
RUN bash Anaconda3-2020.02-Linux-x86_64.sh -b -p /opt/conda
RUN rm Anaconda3-2020.02-Linux-x86_64.sh

# Set path to conda
ENV PATH=/opt/conda/bin:$PATH

# Updating Anaconda packages
RUN conda update conda
RUN conda update anaconda
RUN conda update --all
RUN export ADD=shiny && bash /etc/cont-init.d/add
